name       : socat
version    : 1.7.3.4
release    : 4
source     :
    - http://www.dest-unreach.org/socat/download/socat-1.7.3.4.tar.gz : d9ed2075abed7b3ec9730ed729b4c8e287c502181c806d4487020418a6e2fc36
license    : GPL-2.0-or-later
component  : network.util
summary    : Bidirectional data transfer relay
description: |
    socat is a relay for bidirectional data transfer between two independent data channels. Each of these data channels may be a file, pipe, device (serial line or a pseudo terminal), a socket (UNIX, IP4, IP6 - raw, UDP, TCP), an SSL socket, proxy CONNECT connection, a file descriptor (stdin etc.), the GNU line editor (readline), a program, or a combination of two of these. These modes include generation of "listening" sockets, named pipes, and pseudo terminals.
builddeps  :
    - openssl-11-devel
environment: |
    export CFLAGS="${CFLAGS} -Wno-deprecated-declarations"
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-use-of-DH_set0_pqg.patch
    %configure
build      : |
    %make
install    : |
    %make_install
